---

-   debconf:
        name: '{{ item.name }}'
        question: '{{ item.question }}'
        value: '{{ item.value }}'
        vtype: '{{ item.vtype }}'

    with_items:
        -   name: unattended-upgrades
            question: unattended-upgrades/enable_auto_updates
            value: true
            vtype: boolean
        -   name: ca-certificates
            question: ca-certificates/trust_new_crts
            value: ask
            vtype: string

-   script: >
        files/remove-certificates
            mozilla/China_Internet_Network_Information_Center_EV_Certificates_Root.crt
            mozilla/CNNIC_ROOT.crt
            mozilla/ePKI_Root_Certification_Authority.crt
            mozilla/Hongkong_Post_Root_CA_1.crt
            mozilla/Taiwan_GRCA.crt
            mozilla/TWCA_Global_Root_CA.crt
            mozilla/TWCA_Root_Certification_Authority.crt
            mozilla/WoSign_China.crt
            mozilla/WoSign.crt
