---
- hosts: '{{ hosts }}'
  become: true
  become_user: root
  vars:
    ppa_ubuntu_codename: bionic
    debian_codename: buster
    apt_keyserver: pool.sks-keyservers.net

  roles:
    - security
    - debian_repository
    - base
    - developer
    - desktop
