#!/bin/bash
set -e
set -u

command -v certutil

NSSDB=sql:${HOME}/.pki/nssdb
CRT_DIR="revoked_certificates"

for crt in ${CRT_DIR}/*.crt; do
    name=$(basename ${crt})
    certutil -d ${NSSDB} -A -n ${name} -t p,p,p -i ${crt}
done

certutil -L -d ${NSSDB}
