#!/bin/bash
set -e
set -u

NSSDB_PATH=sql:${HOME}/.pki/nssdb

BAD_CA_NAMES=(
    "CA WoSign ECC Root"
    "Certification Authority of WoSign G2"
    "CNNIC ROOT"
    "StartCom Certification Authority"
    "StartCom Certification Authority"
    "StartCom Certification Authority G2"
    "WoSign"
    "WoSign China"
)

for ca_name in "${BAD_CA_NAMES[@]}"; do
    certutil -d ${NSSDB_PATH} -M -n "${ca_name}" -t p,p,p
done

certutil -L -d ${NSSDB_PATH}
