#!/bin/bash
set -e
set -u

command -v certutil

NSSPATHS="$(echo ${HOME}/.mozilla/firefox/*.default) ${HOME}/.pki/nssdb"
CRT_DIR="revoked_certificates"

for nss_path in $NSSPATHS; do
    for crt in ${CRT_DIR}/*.crt; do
        name=$(basename ${crt})
        certutil -d sql:${nss_path} -A -n ${name} -t p,p,p -i ${crt}
    done
    echo "===> Certificate in ${nss_path}"
    certutil -L -d sql:${nss_path}
done

