---

-   debconf:
        name: '{{ item.name }}'
        question: '{{ item.question }}'
        value: '{{ item.value }}'
        vtype: '{{ item.vtype }}'

    with_items:
        -   name: unattended-upgrades
            question: unattended-upgrades/enable_auto_updates
            value: true
            vtype: boolean
        -   name: ca-certificates
            question: ca-certificates/trust_new_crts
            value: ask
            vtype: string
