---

-   debconf:
        name: '{{ item.name }}'
        question: '{{ item.question }}'
        value: '{{ item.value }}'
        vtype: '{{ item.vtype }}'

    with_items:
        -   name: unattended-upgrades
            question: unattended-upgrades/enable_auto_updates
            value: 'true'
            vtype: string
        -   name: unattended-upgrades
            question: unattended-upgrades/origins_pattern
            value: '"origin=Debian,codename=${distro_codename},label=Debian-Security";'
            vtype: string
        -   name: ca-certificates
            question: ca-certificates/trust_new_crts
            value: ask
            vtype: string

# https://pierrekim.github.io/blog/2016-02-16-why-i-stopped-using-startssl-because-of-qihoo-360.html
-   script: >
        files/remove-certificates
            mozilla/CA_WoSign_ECC_Root.crt
            mozilla/Certification_Authority_of_WoSign_G2.crt
            mozilla/China_Internet_Network_Information_Center_EV_Certificates_Root.crt
            mozilla/CNNIC_ROOT.crt
            mozilla/ePKI_Root_Certification_Authority.crt
            mozilla/Hongkong_Post_Root_CA_1.crt
            mozilla/StartCom_Certification_Authority_2.crt
            mozilla/StartCom_Certification_Authority_2.crt
            mozilla/StartCom_Certification_Authority_G2.crt
            mozilla/StartCom_Certification_Authority.crt
            mozilla/Taiwan_GRCA.crt
            mozilla/TWCA_Global_Root_CA.crt
            mozilla/TWCA_Root_Certification_Authority.crt
            mozilla/WoSign_China.crt
            mozilla/WoSign.crt
