---

# https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install

- name: confluent
  apt_key:
    url: https://packages.confluent.io/deb/5.1/archive.key

- name: confluent
  apt_repository:
    repo: deb [arch=amd64] https://packages.confluent.io/deb/5.1 stable main
    filename: confluent
