---

# https://www.insynchq.com/downloads

-   name: insync
    apt_key:
        id: AEEB94E9C5A3B54ECFA4A66AA684470CACCAF35C
        keyserver: '{{ apt_keyserver }}'

-   name: insync
    apt_repository:
        repo: deb http://apt.insynchq.com/debian sid non-free contrib
        filename: insync
