---

# https://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/

-   name: mongodb
    apt_key:
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        keyserver: '{{ apt_keyserver }}'

-   name: mongodb
    apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
        filename: mongodb
