---

-   apt_key:
        id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
        keyserver: '{{ apt_keyserver }}'

-   apt_repository:
        repo: '{{ item }}'
        filename: dropbox
    with_items:
        -   'deb http://linux.dropbox.com/debian sid main'
        -   'deb-src http://linux.dropbox.com/debian sid main'

-   apt:
        name: dropbox
