---

# https://repo.skype.com/

-   apt_key:
        url: https://repo.skype.com/data/SKYPE-GPG-KEY


-   apt_repository:
        repo: '{{ item }}'
        filename: skype
    with_items:
        -   'deb [arch=amd64] https://repo.skype.com/deb stable main'

-   apt:
        name: '{{ item.name }}'

    with_items:
        -   name: skypeforlinux
