---

- name: install packages
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    purge: 'yes'

  with_items:
    - name: apt-file
    - name: apt-listchanges
    - name: code
    - name: crun
    - name: dnsutils
    - name: dstat
    - name: fonts-jetbrains-mono
    - name: fzf
    - name: git
    - name: gnupg2
    - name: goobook
    - name: graphviz
    - name: gufw
    - name: ledger
    - name: libpam-yubico
    - name: libtool
    - name: libu2f-udev  # For U2F security key
    - name: lsb-release
    - name: lshw
    - name: lxc
    - name: msmtp
    - name: mutt
    - name: ncdu
    - name: needrestart
    - name: net-tools
    - name: network-manager-openvpn-gnome
    - name: network-manager-pptp  # for VPN
    - name: nmap
    - name: npm
    - name: ntp
    - name: p7zip-full
    - name: parcimonie
    - name: pass
    - name: pinfo
    - name: pipx
    - name: podman
    - name: ratt
    - name: ripgrep
    - name: rr
    - name: scdaemon
    - name: signing-party
    - name: snapd
    - name: sudo
    - name: sysstat
    - name: tig
    - name: tiptop
    - name: tmux
    - name: tree
    - name: unattended-upgrades
    - name: vim-gtk  # For system clipboard
    - name: voltron
    - name: yadm
    - name: yamllint
    - name: yapf3
    - name: yarn
    - name: yubikey-manager
    - name: zplug
    - name: zsh
