---
-   hosts: '{{ hosts }}'
    become: true
    become_user: root
    vars:
        ppa_ubuntu_codename: xenial
        stable_debian_codename: jessie
        apt_keyserver: pool.sks-keyservers.net
        debian_repo: http://httpredir.debian.org/debian/
        debian_debug_repo: http://debug.mirrors.debian.org/debian-debug/
        debian_suite: main contrib non-free

    roles:
        -   base
        -   security
        -   developer

        -   atom
        -   dropbox
        -   gitlab
        -   google-chrome
        -   mongodb
        -   sbt
        -   sublime-text
        -   syncthing
